[project]
name = "py-tracer"
version = "0.1.0"
dependencies = [
    "jsonpickle",
]

[project.optional-dependencies]
all = [
    "pytest",
    "pydantic",
    "numpy",
    "pandas",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["tracer", "tracer_plugin", "tracer.*", "tracer_plugin.*"]

[project.entry-points.pytest11]
tracer_plugin = "tracer_plugin.pytest_plugin"